### ISSUE TITLE
can't pair dji Moonlight to Shield

### ISSUE THREAD

**Issue by postrealms** [fpv-wtf/dji-moonlight-gui#4] opened 2023-12-27 15:00 UTC
after some time of not using my dji goggles v2 via Moonlight ive lost this line. Now im trying to pair them again but without any luck.
Sorry to borher you but i need your help

Regards, Max

**Comment by j005u** [comment] 2024-01-02 21:39
Please try the workaround shown here until we figure this out: https://github.com/fpv-wtf/dji-moonlight-gui/issues/3#issuecomment-1869162170

Closing as it this is a duplicate of #3.

**Closed by j005u** 2024-01-02 21:39 UTC
